version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3033:3033
    command: node disksharing.js
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always